import {
  Aganyin,
  Amala,
  AmamaBig,
  Dalgety,
  DalgetyHoney,
  Eforiri,
  EgusiSoup,
  Fufu,
  Garri,
  GerlicPaste,
  GingerPaste,
  Lafun,
  LafunBig,
  OfadaSourse,
  Pap,
  PapBig,
  PeanutButter,
  PlantainAmala,
  PlantainAmalaBig,
  PlantainChips,
  PlantainChips2,
  PlantainChips3,
  Product1,
  Product2,
  Product3,
  Product4,
  PunaYam,
  Semolina,
  SemolinaBig,
  Semovita,
  SemovitaBig,
  Starch,
  StarchBig,
  Tuwo,
  TuwoBig,
  WakyeLead,
  Wheat,
  WheatBig,
  WheatBig2,
  WheatBig3,
} from "../assets";

export const AdvertMessage = [
  {
    id: 1,
    text: "We got you covered for good selection for christmas",
    image: "",
    to: "",
    backGroundImg: "",
  },
  {
    id: 2,
    text: "Merry Christmas and Happy new year",
    image: "",
    to: "/Mall",
    backGroundImg: "",
  },
  {
    id: 3,
    text: "We will never call you for yuur card etails",
    image: "",
    to: "/Mall",
    backGroundImg: "",
  },
  {
    id: 4,
    text: "Shop on budget and tust us with your enjoyment",
    image: "",
    to: "/Mall",
    backGroundImg: "",
  },
  {
    id: 5,
    text: "By one and get 20 free",
    image: "",
    to: "/school",
    backGroundImg: "",
  },
  {
    id: 6,
    text: "Protect your card details",
    image: "",
    to: "",
    backGroundImg: "",
  },
];

export const sliderCard = [
  {
    id: 7,
    style: "carousel1",
    productImg: Product1,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "POUNDO YARM FLOUR 'IYAN'",
    categories: [
      "Food",
      "keg",
      "Grains and Flours",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 8,
    style: "carousel1",
    productImg: Product2,
    collectionTitle:
      "Special Offer: First 50 Guests Receive a Complimentary Dessert!",
    collectionDecription:
      "Don't miss out on the chance to experience culinary excellence at Gourmet Delights. Reserve your table now, and be one of the first 50 guests to enjoy a complimentary dessert that will sweeten your dining adventure.",

    // productCard
    title: "EGGPLANT SWALLOW",
    categories: [
      "Food",
      "keg",
      "Grains and Flours",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 9,
    style: "carousel1",
    productImg: Product3,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "CABBAGE SWALLOW",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 10,
    style: "carousel1",
    productImg: Product4,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "POUNDO YARM FLOUR",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 11,
    style: "carousel1",
    productImg: Product4,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "POUNDO YARM FLOUR",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 12,
    style: "carousel1",
    productImg: Product4,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "POUNDO YARM FLOUR",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 13,
    style: "carousel1",
    productImg: Product4,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "POUNDO YARM FLOUR",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 14,
    style: "carousel1",
    productImg: Product4,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "POUNDO YARM FLOUR",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
];

export const readyMade = [
  {
    id: 15,
    style: "carousel1",
    productImg: Eforiri,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "Eforiro Soup",
    categories: [
      "Food",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 16,
    style: "carousel1",
    productImg: OfadaSourse,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "Ofada Sauce",
    categories: [
      "Food",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 17,
    style: "carousel1",
    productImg: EgusiSoup,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "Egusi Soup",
    categories: [
      "Food",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 18,
    style: "carousel1",
    productImg: Aganyin,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "Temi Aganyin Pepper Sauce Mix",
    categories: [
      "Food",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 19,
    style: "carousel1",
    productImg: WakyeLead,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "Wakye Leaf",
    categories: [
      "Food",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 20,
    style: "carousel1",
    productImg: Dalgety,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "Dalgety effective slimline tea 40g",
    categories: [
      "Food",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 21,
    style: "carousel1",
    productImg: PunaYam,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "Puna Yam",
    categories: [
      "Food",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 22,
    style: "carousel1",
    productImg: DalgetyHoney,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "Dalgety honey and ginger tea 40g",
    categories: [
      "Food",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 23,
    style: "carousel1",
    // productImg: Product4,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "Ofada Sauce",
    categories: [
      "Food",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 24,
    style: "carousel1",
    // productImg: Product4,
    collectionTitle: "Savor the Flavor: Unforgettable Culinary Creations",
    collectionDecription:
      "From savory starters to mouthwatering mains, our menu is a celebration of flavors from around the world. Try our signature [dish name], a symphony of perfectly balanced ingredients that will transport you to food paradise.",

    // productCard
    title: "Ofada Sauce",
    categories: [
      "Food",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
];

export const smallPack = [
  {
    id: 25,
    style: "carousel1",
    productImg: Garri,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Garri",
    categories: [
      "Food",
      "bag",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 26,
    style: "carousel1",
    productImg: Amala,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Amala Yam flour",
    categories: [
      "Food",
      "bag",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 27,
    style: "carousel1",
    productImg: Wheat,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Wheat flour",
    categories: [
      "Food",
      "bag",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 28,
    style: "carousel1",
    productImg: PlantainAmala,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Plantain Aamala",
    categories: [
      "Food",
      "bag",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 29,
    style: "carousel1",
    productImg: Fufu,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Fufu Flour",
    categories: [
      "Food",
      "bag",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 30,
    style: "carousel1",
    productImg: Semolina,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Semolina",
    categories: [
      "Food",
      "bag",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 31,
    style: "carousel1",
    productImg: Semovita,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Semovita",
    categories: [
      "Food",
      "bag",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 32,
    style: "carousel1",
    productImg: Pap,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Pap",
    categories: [
      "Food",
      "bag",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 33,
    style: "carousel1",
    productImg: Tuwo,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Tuwo Shinkafa",
    categories: [
      "Food",
      "bag",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 34,
    style: "carousel1",
    productImg: Starch,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Starch",
    categories: [
      "Food",
      "bag",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 35,
    style: "carousel1",
    productImg: Lafun,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Lafun",
    categories: [
      "Food",
      "bag",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
];

export const bigPack = [
  {
    id: 36,
    style: "carousel1",
    productImg: AmamaBig,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Amala Yam flour (Big)",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 37,
    style: "carousel1",
    productImg: WheatBig,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Wheat flour (Big)",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 38,
    style: "carousel1",
    productImg: WheatBig2,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Wheat flour (Big)",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 39,
    style: "carousel1",
    productImg: WheatBig3,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Wheat flour (Big)",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 40,
    style: "carousel1",
    productImg: PlantainAmalaBig,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Plantain Aamala (Big)",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 41,
    style: "carousel1",
    productImg: SemolinaBig,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Semolina (Big)",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 42,
    style: "carousel1",
    productImg: SemovitaBig,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Semovita (Big)",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 43,
    style: "carousel1",
    productImg: PapBig,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Pap (Big)",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 44,
    style: "carousel1",
    productImg: TuwoBig,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Tuwo Shinkafa (Big)",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 45,
    style: "carousel1",
    productImg: StarchBig,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Starch (Big)",
    categories: [
      "Food",
      "keg",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
  {
    id: 46,
    style: "carousel1",
    productImg: LafunBig,
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",

    // productCard
    title: "Lafun (Big)",
    categories: [
      "Food",
      "keg",
      "Grains and Flours",
      "Health and wellness",
      "Popular product",
      "Recently added",
      "Ready made food",
      "Packaged food",
    ],
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
  },
];

// iuy
import {
  AllSpice,
  AlligatorPepper,
  AllspiceSpice,
  AniseSeed,
  BayLeaves,
  BeansPowderBag,
  BlackPepper,
  CalabashNutmeg,
  CameroonPepper,
  CayennePepper,
  CeleryHerb,
  Chicken,
  ChilliPepper,
  ChivesHerbs,
  CilantroHerbs,
  CinnamonSpice,
  CoconutFlourBag,
  ColvesSpice,
  ColvesSpice2,
  CoriaderSeeds,
  CowTongues,
  CuminSpice,
  CuminSpice2,
  DillHerbs,
  DryFish,
  DryPeriwinkle,
  DrySnail,
  EggplantFlourKeg,
  FennelSeed,
  FenugreekSpice,
  GabbageFlourKeg,
  GalicSalt,
  GarlicPowder,
  GarriIjebuBag,
  GingerSpice,
  GoatMeat,
  LafunBag,
  MaceSpice,
  MarjoramBerbs,
  MintLeaves,
  MustardSeeds,
  NegroPepper,
  NutmegSpice,
  OatFiber,
  Oregano,
  PanlasStockFish,
  PaprikaSpice,
  ParsleyHerbs,
  PeeledBeansBag,
  Pork,
  PoundedYamFlourKeg,
  RosemaryHerbs,
  SaffronSpace,
  SageHerbs,
  SesameSeeds,
  Snail,
  StarAniseSpice,
  StarchFlourbag,
  StockFish,
  Thyme,
  TumericSpice,
  WheatFlour,
  YellowGarriBag,
} from "../assets/img";

export const newProduct = [
  // {
  //   id: 51,
  //   productImg: Pork,
  //   title: "Pork",
  //   priceNgn: "10000",
  //   priceUs: "40",
  //   priceUk: "30",
  //   priceGhana: "140",
  //   ngeriaCode: "#",
  //   ghanaCode: "GHS",
  //   ukCode: "GBP",
  //   usCode: "$",
  //   priceCanada: "300",
  //   canadaCode: "CAD",
  //   categories: ["Meat and Seafoods", "Health and wellness"],
  //   collectionTitle: "Food: Discover Culinary Excellence!",
  //   collectionDecription:
  //     "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  // },
  {
    id: 52,
    productImg: CowTongues,
    title: "Cow Tongues",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Meat and Seafoods", "Health and wellness"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 53,
    productImg: Snail,
    title: "Snail",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Meat and Seafoods", "Health and wellness"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 54,
    productImg: NegroPepper,
    title: "Negro Pepper",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 55,
    productImg: WheatFlour,
    title: "Wheat Flour",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Grains and Flours"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 56,
    productImg: TumericSpice,
    title: "Tumeric Spice",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 57,
    productImg: AllspiceSpice,
    title: "Allspice Spice",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 58,
    productImg: StockFish,
    title: "Stock Fish",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 59,
    productImg: AllSpice,
    title: "All Spice",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 60,
    productImg: CayennePepper,
    title: "Cayenne Peppere",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 61,
    productImg: PaprikaSpice,
    title: "Paprika Spice",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 62,
    productImg: GalicSalt,
    title: "Galic Salt",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 63,
    productImg: ColvesSpice,
    title: "Colves Spice",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 64,
    productImg: AniseSeed,
    title: "Anise Seed",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 65,
    productImg: GingerSpice,
    title: "Ginger Spice",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 66,
    productImg: ColvesSpice2,
    title: "Colves Spice Blended",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 67,
    productImg: CuminSpice,
    title: "Cumin spice",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 68,
    productImg: NutmegSpice,
    title: "Nutmeg Spice",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 69,
    productImg: Thyme,
    title: "Thyme",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 70,
    productImg: CameroonPepper,
    title: "Cameroon Pepper",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 71,
    productImg: Chicken,
    title: "Chicken",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 72,
    productImg: CinnamonSpice,
    title: "Cinnamon Spice",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 73,
    productImg: ChilliPepper,
    title: "Chilli Pepper",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 74,
    productImg: CuminSpice2,
    title: "Cumin Spice",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 75,
    productImg: FenugreekSpice,
    title: "Fenugreek Spice",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 76,
    productImg: SaffronSpace,
    title: "Saffron Space",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 77,
    productImg: BlackPepper,
    title: "Black Pepper",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 78,
    productImg: AlligatorPepper,
    title: "Alligator Pepper",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 79,
    productImg: CalabashNutmeg,
    title: "Calabash Nutmeg",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 80,
    productImg: GarlicPowder,
    title: "Garlic Powder",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 81,
    productImg: StarAniseSpice,
    title: "Star Anise Spice",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 82,
    productImg: OatFiber,
    title: "Oat Fiber",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Grains and Flours", "bag"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 83,
    productImg: LafunBag,
    title: "Lafun",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Grains and Flours", "bag"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 84,
    productImg: BeansPowderBag,
    title: "Beans Powder",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Grains and Flours", "bag"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 85,
    productImg: PeeledBeansBag,
    title: "Peeled Beans",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Grains and Flours", "bag"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 86,
    productImg: EggplantFlourKeg,
    title: "Eggplant Flour",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Grains and Flours", "keg"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 87,
    productImg: MaceSpice,
    title: "Mace Spice",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Condiments", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 88,
    productImg: GabbageFlourKeg,
    title: "Gabbage Flour",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Grains and Flours", "keg"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 89,
    productImg: PoundedYamFlourKeg,
    title: "Pounded Yam Flour",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Grains and Flours", "keg"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 90,
    productImg: StarchFlourbag,
    title: "Starch Flour",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Grains and Flours", "bag"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 91,
    productImg: GarriIjebuBag,
    title: "Garri Ijebu",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Grains and Flours", "bag"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 92,
    productImg: YellowGarriBag,
    title: "Yellow Garri",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Grains and Flours", "bag"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 93,
    productImg: YellowGarriBag,
    title: "Beans Ewa Oloyin",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Grains and Flours", "bag"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 94,
    productImg: CoconutFlourBag,
    title: "Coconut Flour",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Grains and Flours", "bag"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 95,
    productImg: DryPeriwinkle,
    title: "Dry Periwinkle",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Meat and Seafoods", "Health and wellness"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 96,
    productImg: PanlasStockFish,
    title: "Panla Stock Fish",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Meat and Seafoods", "Health and wellness"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  // {
  //   id: 97,
  //   productImg: GoatMeat,
  //   title: "Goat Meat",
  //   priceNgn: "10000",
  //   priceUs: "40",
  //   priceUk: "30",
  //   priceGhana: "140",
  //   ngeriaCode: "#",
  //   ghanaCode: "GHS",
  //   ukCode: "GBP",
  //   usCode: "$",
  //   priceCanada: "300",
  //   canadaCode: "CAD",
  //   categories: ["Meat and Seafoods", "Health and wellness"],
  //   collectionTitle: "Food: Discover Culinary Excellence!",
  //   collectionDecription:
  //     "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  // },
  {
    id: 98,
    productImg: DrySnail,
    title: "Dray Snail",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Meat and Seafoods", "Health and wellness"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 99,
    productImg: DryFish,
    title: "Dray Fish",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Meat and Seafoods", "Health and wellness"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 100,
    productImg: CeleryHerb,
    title: "Celery Herb",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 101,
    productImg: MintLeaves,
    title: "Mint Leaves",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable", "Spicies"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 102,
    productImg: MarjoramBerbs,
    title: "Marjoram Berbs",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 103,
    productImg: Oregano,
    title: "Oregano",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 104,
    productImg: RosemaryHerbs,
    title: "Rosemary Herbs",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 105,
    productImg: BayLeaves,
    title: "Bay Leaves",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 106,
    productImg: ChivesHerbs,
    title: "Chives Herbs",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 107,
    productImg: FennelSeed,
    title: "Fennel Seed",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 108,
    productImg: CoriaderSeeds,
    title: "Coriader Seeds",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 109,
    productImg: ParsleyHerbs,
    title: "Parsley Herbs",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 110,
    productImg: CilantroHerbs,
    title: "Cilantro Herbs",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 111,
    productImg: SesameSeeds,
    title: "Sesame Seeds",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 112,
    productImg: SageHerbs,
    title: "Sage Herbs",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 113,
    productImg: DillHerbs,
    title: "Dill Herbs",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 114,
    productImg: DillHerbs,
    title: "Dill Herbs",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 115,
    productImg: MustardSeeds,
    title: "Mustard Seeds",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },

  {
    id: 116,
    productImg: GerlicPaste,
    title: "Gerlic Paste",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["African Snakks"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 117,
    productImg: GingerPaste,
    title: "Ginger Paste",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 118,
    productImg: PeanutButter,
    title: "Peanut Butter",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 119,
    productImg: PlantainChips,
    title: "Plantain Chips",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 120,
    productImg: PlantainChips2,
    title: "Plantain Chips",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
  {
    id: 121,
    productImg: PlantainChips3,
    title: "Plantain Chips",
    priceNgn: "10000",
    priceUs: "40",
    priceUk: "30",
    priceGhana: "140",
    ngeriaCode: "#",
    ghanaCode: "GHS",
    ukCode: "GBP",
    usCode: "$",
    priceCanada: "300",
    canadaCode: "CAD",
    categories: ["Fruits and Vegetable"],
    collectionTitle: "Food: Discover Culinary Excellence!",
    collectionDecription:
      "Are you ready to embark on a gastronomic journey like no other? Look no further than Gourmet Delights – where every dish is a masterpiece crafted to perfection. Our chefs blend passion and creativity to bring you an exquisite dining experience that tantalizes your taste buds.",
  },
];

export const allProduct = newProduct.concat(
  sliderCard,
  bigPack,
  smallPack,
  readyMade
);

export const categories = [
  {
    id: 4,
    category: "Condiments",
  },
  {
    id: 5,
    category: "Meat and Seafoods",
  },
  {
    id: 6,
    category: "Grains and Flours",
  },
  {
    id: 7,
    category: "Health and wellness",
  },
  {
    id: 8,
    category: "Fruits and Vegetable",
  },
  {
    id: 1,
    category: "bag",
  },
  {
    id: 2,
    category: "keg",
  },
  {
    id: 3,
    category: "Spicies",
  },
];
